### ISSUE TITLE
Next Meeting? This week or next?

### ISSUE THREAD

**Issue by christophwille** [Azure/aks-gbb-officehours#4]
According to the README, it is 12th. According to the calendar invite it is tomorrow 5th. Which one is correct?

**Comment by christophwille** [comment]
README seems to have been updated & fixed. Closing.

**Comment by kendallroden** [comment]
Hey thanks for this @christophwille I think the calendar invite is messed up still- made an announcement today but will recreate that and upload. Thanks again :)

**Comment by Luizfstoledo** [comment]
> Ei, obrigado por este @christophwille , acho que o convite do calendário ainda está bagunçado - fiz um anúncio hoje, mas vou recriá-lo e fazer o  #upload
Duplicate of #. Obrigado novamente :)

**Comment by Luizfstoledo** [comment]
E
