### ISSUE TITLE
office hour email

### ISSUE THREAD

**Issue by lazydino** [Azure/aks-gbb-officehours#5]
AKS office hours email is not delivered from my end? Is it opened to the public?

**Comment by kendallroden** [comment]
Will check on this thanks for letting us know!

**Comment by nreisbeck** [comment]
> Will check on this thanks for letting us know! 

@kendallroden the aksofficehours@microsoft.com email address is still not configured to accept external emails. Can you please resolve this configuration error?

**Comment by mwilsonray** [comment]
> > Will check on this thanks for letting us know!
> 
> @kendallroden the [aksofficehours@microsoft.com](mailto:aksofficehours@microsoft.com) email address is still not configured to accept external emails. Can you please resolve this configuration error?

Still not accepting external emails ....

**Comment by Agger1995** [comment]
> 
> 
> > > Will check on this thanks for letting us know!
> > 
> > 
> > @kendallroden the [aksofficehours@microsoft.com](mailto:aksofficehours@microsoft.com) email address is still not configured to accept external emails. Can you please resolve this configuration error?
> 
> Still not accepting external emails ....

I am also experiencing an error, stating that my email was not delivered.

**Comment by nreisbeck** [comment]
@mwilsonray @Agger1995 

I attended the office hours a few weeks ago and mentioned this to @kendallroden. She said she would work on tracking down the problem and fixing the distribution list. 

Might be worth dropping by the next meeting to resurface the issue.
